version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    volumes:
      - .:/app  # Mount the current directory to /app in the container

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data across container restarts

volumes:
  db_data:

