version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

